main: me.BryanBarren.Economy.Main
version: 1.0
author: Bryan
description: A companies plugins for McCities
name: McCitiesCompanies
commands:
  company:
    description: This is the core command for the companies plugin.
    usage: /company